export const tables = {
  PRADAtable: [
    {
      Rank: 1,
      Company: {
        CompanyName: "veda",
        CompanyField: "Healthtech, Machine Learning",
        CompanyLocation: "Madison, WI",
        CompanyLogo: "veda.png",
        },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 2,
      Company: {
        CompanyName: "involve.ai",
        CompanyField: "Software, Professional Services",
        CompanyLocation: "Los Angeles, CA",
        CompanyLogo: "involveai.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 3,
      Company: {
        CompanyName: "Urbint",
        CompanyField: "Machine Learning, Analytics",
        CompanyLocation: "NYC",
        CompanyLogo: "urbint.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 4,
      Company: {
        CompanyName: "Circulo Health",
        CompanyField: "Healthcare",
        CompanyLocation: "Columbus, OH",
        CompanyLogo: "circulohealth.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 5,
      Company: {
        CompanyName: "CCC",
        CompanyField: "Automotive + Insurance",
        CompanyLocation: "Chicago, IL",
        CompanyLogo: "ccc.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 6,
      Company: {
        CompanyName: "Veritone",
        CompanyField: "Big Data",
        CompanyLocation: "Costa Mesa, CA",
        CompanyLogo: "veritone.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 7,
      Company: {
        CompanyName: "LogicMonitor",
        CompanyField: "Software",
        CompanyLocation: "New York, NY",
        CompanyLogo: "logicmonitor.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 8,
      Company: {
        CompanyName: "Nate",
        CompanyField: "E-commerce",
        CompanyLocation: "New York, NY",
        CompanyLogo: "nate.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 9,
      Company: {
        CompanyName: "People.ai",
        CompanyField: "Software",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "peopleai.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 10,
      Company: {
        CompanyName: "Riskified",
        CompanyField: "E-commerce",
        CompanyLocation: "New York, NY",
        CompanyLogo: "riskified.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 11,
      Company: {
        CompanyName: "Moveworks",
        CompanyField: "Information Technology",
        CompanyLocation: "Mountain View, CA",
        CompanyLogo: "moveworks.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 12,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "Grammarly.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 13,
      Company: {
        CompanyName: "AlphaSense",
        CompanyField: "Fintech",
        CompanyLocation: "New York, NY",
        CompanyLogo: "alphasense.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 14,
      Company: {
        CompanyName: "Tempus",
        CompanyField: "Healthtech, Biotech, Big Data",
        CompanyLocation: "Chicago, IL",
        CompanyLogo: "tempus.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 15,
      Company: {
        CompanyName: "Ascent",
        CompanyField: "RegTech, Fintech, Legal",
        CompanyLocation: "Chicago, IL",
        CompanyLogo: "ascent.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 16,
      Company: {
        CompanyName: "Narrative Science Name",
        CompanyField: "Big Data, Software",
        CompanyLocation: "Chicago, IL",
        CompanyLogo: "narrativesciencename.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 17,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 18,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 19,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 20,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 21,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 22,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 23,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 24,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 25,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 26,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 27,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 28,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 29,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 30,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 31,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 32,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 33,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 34,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 35,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 36,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 37,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 38,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 39,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 40,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 41,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 42,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
  ],

  Platformtable: [
    {
      Rank: 1,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 2,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
  ],

  Researcherstable: [
    {
      Rank: 1,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 2,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
  ],

  Algorithmtable: [
    {
      Rank: 1,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 2,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 3,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 4,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 5,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 6,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 7,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 8,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 9,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 10,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 11,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 12,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 13,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 14,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 15,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 16,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 17,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 18,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
  ],

  Datatable: [
    {
      Rank: 1,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 2,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
  ],

  Applicationstable: [
    {
      Rank: 1,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 2,
      Company: {
        CompanyName: "Grammarly",
        CompanyField: "Company Summary",
        CompanyLocation: "San Francisco, CA",
        CompanyLogo: "ntu.png",
      },
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
  ],
};
