export const tables = {
  PRADAtable: [
    {
      Rank: 1,
      Company: "veda",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 2,
      Company: "involved.ai",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 3,
      Company: "CCC",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 4,
      Company: "Circulo Health",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 5,
      Company: "Veritone",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 6,
      Company: "LogicMonitor",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 7,
      Company: "Nate",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 8,
      Company: "People.ai",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 9,
      Company: "Moveworks",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 10,
      Company: "Grammarly",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 11,
      Company: "AlphaSense",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 12,
      Company: "Tempus",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 13,
      Company: "Ascent",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 14,
      Company: "Narrative Science Name",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 15,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 16,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 17,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 18,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 19,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 20,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 21,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 22,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 23,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 24,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 25,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 26,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 27,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 28,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 29,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 30,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 31,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 32,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 33,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 34,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 35,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 36,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 37,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 38,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 39,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 40,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 41,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 42,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
  ],

  Platformtable: [
    {
      Rank: 1,
      Company: "Nate",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 2,
      Company: "Urbint",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
  ],

  Researcherstable: [
    {
      Rank: 1,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 2,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
  ],

  Algorithmtable: [
    {
      Rank: 1,
      Company: "Nate",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 2,
      Company: "Urbint",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 3,
      Company: "Nate",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 4,
      Company: "Urbint",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 5,
      Company: "Nate",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 6,
      Company: "Urbint",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 7,
      Company: "Nate",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 8,
      Company: "Urbint",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 9,
      Company: "Nate",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 10,
      Company: "Urbint",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 11,
      Company: "Nate",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 12,
      Company: "Urbint",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 13,
      Company: "Nate",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 14,
      Company: "Urbint",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 15,
      Company: "Nate",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 16,
      Company: "Urbint",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 17,
      Company: "Nate",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 18,
      Company: "Urbint",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
  ],

  Datatable: [
    {
      Rank: 1,
      Company: "Riskified",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
    {
      Rank: 2,
      Company: "Urbint",
      Platform: 4.9,
      Researchers: 7.9,
      Algorithm: 9.8,
      Data: 8.7,
      Applications: 9.4,
    },
  ],

  Applicationstable: [
    {
      Rank: 1,
      Company: "Nate",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
    {
      Rank: 2,
      Company: "Urbint",
      Publications: 4.9,
      Patents: 35,
      Number_of_articles: 183,
      Algorithm: 9.4,
    },
  ],
};
